### ISSUE TITLE
1.180370 cannot download from HTTP addresses

### ISSUE THREAD

**Issue by ppisar** [petrkle/webservice-rajce#5]
1.180370 replaced fixed https schema, but broke http schema. This stopped to work:

```
$ perl -Ilib bin/rajce-get -u 'http://wwendy53.rajce.idnes.cz/Opava_v_dopolednim_slunci/' 
Usage:
    rajce-get [OPTIONS]
[...]
```

The plain HTTP is still supported by the server. If you go to <http://www.rajce.idnes.cz/>, then click to 'Prohlížet', you will get album listing and all of them uses http. Not https.

I think this tool should support both of them.

**Comment by petrkle** [comment]
Thanks for report and patch. Released in [1.180380](https://metacpan.org/release/PEK/WebService-Rajce-1.180380)
