### ISSUE TITLE
rajce-get doesn't download, no clue why despite using -v

### ISSUE THREAD

**Issue by kavol** [petrkle/webservice-rajce#7]
SSIA - trying to use rajce-get, I'm getting only empty directory, and using the --verbose option doesn't lead to any hint what is wrong

$ rajce-get -v -u https://denebcino.rajce.idnes.cz/Luzicke_Bloudeni_2020
Creating directory denebcino/Luzicke_Bloudeni_2020
$ ls -R denebcino
denebcino:
Luzicke_Bloudeni_2020

denebcino/Luzicke_Bloudeni_2020:
$ rajce-get -V
1.190840

**Comment by petrkle** [comment]
I belive that 2ccec36 fix downloading.
